# Uncomment the next line to define a global platform for your project
platform :ios, "10.0"
inhibit_all_warnings!
source 'https://cdn.cocoapods.org/'
#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
#source 'https://github.com/slkai/Specs.git'
#source 'https://github.com/CocoaPods/Specs.git'

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

target ’XYRefreshControl’ do
  
      pod 'Texture', "= 2.8.1"
end

 
